// Auto-generated by scripts/ingest.mjs — do not edit manually.
// Re-run `npm run ingest` after publishing or unpublishing a blog post.

export const BLOG_SLUGS = [
  "2026-05-12-behind-the-paddle-games",
  "2026-05-14-pipeline-writes-my-blog-posts",
  "2026-05-20-paddle-games-got-a-notifications-inbox",
  "2026-05-21-rater-and-writer-had-different-rules",
  "building-dimeglio-dev-with-ai",
  "mcp-in-production-scheduling",
  "observability-stack",
  "welcome-guillermo-the-ai-agent"
] as const;
