// Auto-generated by scripts/ingest.mjs — do not edit manually.
// Re-run `npm run ingest` after publishing or unpublishing a blog post.

export const BLOG_SLUGS = [
  "building-dimeglio-dev-with-ai",
  "welcome-guillermo-the-ai-agent"
] as const;
